#!/bin/bash

: '
    This script must be used for:
        summasollutions/php:5.6-fpm
        summasollutions/php:7.0-fpm
        summasollutions/php:7.1-fpm
        summasollutions/php:7.1.17-fpm
        summasollutions/php:7.1.26-fpm
'

sudo -E /usr/local/bin/setup-php-modules-summa

docker-php-entrypoint $@